- src/App.tsx
- src/index.tsx
- src/routes/RoutePage.tsx
| feature 병합                             |             ✅          |
- 라우트 기본설정
> [23.02.21] 라우트설정

- src/App.tsx
- src/assets/back.svg
- src/components/header/Header.tsx
- src/components/header/HeaderConstants.ts
- src/components/header/HeaderData.tsx
- 헤더 UI 제작
- 페이지별 헤더 출력
- 헤더 클릭 시 추가 라우트 설정 필요
> [23.02.21] 헤더 추가 PR 요청

- .gitignore
- package-lock.json
- package.json
[날짜] 기능 PR요청
| 기타 (아래에 자세한 내용을 기입해주세요) |         ✅              |
- axios 설치
-
> [23.02.22] axios 설치 머지

- src/apis/authApi.ts
- src/apis/signInApi.ts
- src/pages/signin/SignIn.tsx
- src/pages/signin/SignInConstants.ts
- src/pages/signin/SocialLogin.tsx
> [22.04.12] 소셜로그인

- src/components/header/Header.tsx
| feature 병합                             |             ✅          |
| 버그 수정                                |                ✅       |
- pc화면에서 헤더 좌측 마진 발생하는 문제 수정했습니다.
- 헤더 뒤로가기 버튼을 누르면 뒤로가도록 라우트 설정 했습니다.
-
> [23.02.25] 헤더 수정 PR 요청

- src/components/header/Header.tsx
- 헤더가 가장 위에 위치하도록 z index를 변경하였습니다.
> [23.02.26] 헤더 css 변경

- src/components/splash/Splash.tsx
| feature 병합                             |             ✅          |
- 데스크탑 뷰 스플래시 css 추가
-
-
> [23.02.27] 스플래시 반응형 디자인

- src/apis/authApi.ts
- src/apis/signInApi.ts
- src/pages/signin/SignIn.tsx
- 소셜 - 회원가입 연결
-
- 카카오 로그인추가
- 라이벌리 에러 수정
- 회원가입 후 로그인하도록 구현
> [23.02.27] 소셜로그인 연결

- src/App.tsx
- src/atoms/atom.tsx
- src/components/board/Comments.tsx
- src/components/modals/Modals.tsx
- src/components/modals/UpdateDeleteModal.tsx
- src/hooks/useModal.tsx
- src/pages/board/BoardDetail.tsx
- src/styles/global.css
[날짜] 기능 PR요청
- merge 요청자: @
- 
-
-
> [23.03.12] 머지

- src/apis/boardApi.ts
- src/apis/signInApi.ts
- src/components/board/Comments.tsx
- src/components/board/PostList.tsx
- src/components/modals/CreatePostModal.tsx
- src/components/modals/Modals.tsx
- src/hooks/useIntersectionObserver.ts
- src/hooks/useModal.tsx
- src/hooks/useToggle.tsx
- src/pages/board/BoardDetail.tsx
- src/pages/board/BoardMain.tsx
- src/pages/signin/OauthRedirectHandler.tsx
[날짜] 기능 PR요청
- 게시판 메인페이지 get 연결
- 게시판 상세페이지 get 연결
- 게시판 댓글리스트 get 연결
- 게시판, 댓글 리스트 무한스크롤 구현
-
> [230325] 게시판 조회 api연결

- src/components/navbar/CommandNavbar.tsx
- src/components/navbar/Navbar.tsx
| feature 병합                             |          ✅             |
- 네브바 댓글 작성 UI제작
- 네브바 피그마대로 디자인 조금 수정했습니다! 
-
> [230326] 네브바 댓글작성 UI제작

- src/App.tsx
- src/components/board/PostList.tsx
- src/components/loader/Loader.tsx
- src/components/navbar/Navbar.tsx
- src/pages/board/BoardMain.tsx
- src/styles/global.css
| 버그 수정                                |            ✅           |
- 자잘한 css 오류 수정했습니다.
-
-
> [230327] 자잘한 디자인 오류 수정

- src/apis/boardApi.ts
- src/pages/board/BoardCreate.tsx
- src/styles/global.css
- 글 작성 api 연결했습니다.
- 글 작성 페이지 ui 개선했습니다.
> [230405] 글작성 api 연결

- src/apis/boardApi.ts
- src/apis/signInApi.ts
- src/components/board/Comments.tsx
- src/components/modals/ConfirmModal.tsx
- src/components/modals/Modals.tsx
- src/components/modals/RavelryConnectModal.tsx
- src/components/modals/ReportModal.tsx
- src/components/modals/UpdateDeleteModal.tsx
- src/pages/board/BoardCreate.tsx
- src/pages/board/BoardDetail.tsx
- src/pages/report/ReportPage.tsx
- src/pages/signin/OauthRedirectHandler.tsx
- src/pages/signin/RavelryConnectHandler.tsx
- src/routes/RoutePage.tsx
- src/styles/global.css
> [230409] 라이벌리 연동 기능

- src/apis/signUpApi.ts
- src/pages/signup/SignUp.tsx
| feature 병합                             |             ✅          |
- 회원가입페이지 디자인 디테일 수정
- 이메일 중복확인 api연결
- 회원가입 api연결
-
> [230410] 회원가입 api연결

- src/apis/boardApi.ts
- src/components/modals/UpdateDeleteModal.tsx
- src/pages/board/BoardCreate.tsx
- src/routes/RoutePage.tsx
- 글 수정 api 연결
- 글 수정 시 변경된 사진 배열도 저장됩니다.
> [230412] 글 수정 api 연결

- src/pages/board/BoardCreate.tsx
- 글 수정에서 사진이 삭제가 안되는 오류를 수정했습니다.
- 글 수정 시 수정된 페이지로 이동되도록 했습니다.
> [230414] 글수정에서 사진삭제 오류 수정

- src/apis/authApi.ts
- src/components/header/HeaderConstants.ts
- src/components/header/HeaderData.tsx
- src/components/mypage/MypagePopUp.tsx
- src/pages/mypage/MySetting.tsx
- src/pages/mypage/MypageConstants.ts
- src/routes/RoutePage.tsx
- 기타 설정 페이지 UI와 로그아웃 기능 추가
- 기타 설정페이지의 기타 기능 추가
> [230421] 로그아웃 기능추가

- src/components/board/PostList.tsx
- src/pages/board/BoardMain.tsx
> [230427] 검색 기능 추가

- src/apis/authApi.ts
- 리프레시 토큰이 갱신되지 않는 오류 해결
- 리프레시 토큰 만료 시 로그인으로 리다이렉트 안되는 오류 해결
> [230428] 리프레시토큰 오류 해결

- src/components/board/CommandNavbar.tsx
- src/components/board/Comments.tsx
- src/components/board/PostList.tsx
- src/components/header/Header.tsx
- src/components/modals/ConfirmModal.tsx
- src/components/modals/Modals.tsx
- src/components/modals/StopEditModal.tsx
- src/pages/board/BoardDetail.tsx
- tailwind.config.js
- 게시판 폰트 크기 확대 적용
- 게시판 댓글 작성 폰트 크기 확대
- 댓글 및 게시글 수정 시 벗어나면 수정 취소 모달 추가
- 댓글 삭제, 작성 시 게시판 댓글 수 UI 적용되도록 변경
> [230430] 게시판 디자인 수정 및 수정모달 기능 추가

- src/components/header/Header.tsx
- src/components/images/ImagesDetail.tsx
- src/components/navbar/Navbar.tsx
- src/pages/board/BoardDetail.tsx
- src/routes/RoutePage.tsx
> [230506] 이미지 확대보기 캐러셀

- .eslintrc.js
- src/apis/boardApi.ts
- src/apis/mypageApi.ts
- src/components/board/PostList.tsx
- src/components/header/HeaderConstants.ts
- src/components/header/HeaderData.tsx
- src/components/mypage/MypagePopUp.tsx
- src/hooks/useInfiniteScroll.ts
- src/pages/board/BoardMain.tsx
- src/pages/mypage/MyCommentLog.tsx
- src/pages/mypage/MyPostLog.tsx
- src/routes/RoutePage.tsx
[날짜] 기능 PR요청
| 코드 개선                                |          ✅             |
- 내글조회 기능추가
- 마이페이지 UI변경사항 반영
- 무한스크롤 훅 분리
- 내가 쓴 댓글 조회 기능과 탈퇴하기 기능이 추가되어야합니다.
> [230515] 마이페이지 내글조회

- src/apis/authApi.ts
- src/apis/mypageApi.ts
- src/components/board/CommandNavbar.tsx
- src/components/modals/Modals.tsx
- src/components/modals/WithdrawConfirmModal.tsx
- src/components/modals/WithdrawModal.tsx
- src/components/mypage/MypagePopUp.tsx
- src/pages/board/BoardDetail.tsx
- src/pages/mypage/MySetting.tsx
| feature 병합                             |          ✅             |
- 탈퇴기능 추가
- 프로필 디폴트 사진 추가
-
> [230516] 탈퇴기능 추가

- src/apis/mypageApi.ts
- src/pages/mypage/MyCommentLog.tsx
| feature 병합                             |          ✅             |
- 내가 쓴 댓글 조회 기능추가
> [230519] 내가 쓴 댓글 조회 기능추가

- src/pages/mypage/MypageUpdateForm.tsx
[날짜] 기능 PR요청
- merge 요청자: @
-
-
-
> Feat : 프로필 업데이트 시 쿼리무효화

- src/components/board/CommandNavbar.tsx
- src/components/modals/ProfileUpdateModal.tsx
- src/components/modals/ReportModal.tsx
- src/components/modals/UpdateDeleteModal.tsx
- src/components/mypage/MypagePopUp.tsx
- src/components/toastPopup/ToastPopup.tsx
- src/pages/board/BoardCreate.tsx
- src/pages/mypage/MypageUpdateForm.tsx
- src/styles/global.css
- tailwind.config.js
| 버그 수정                                |            ✅           |
- 글작성, 댓글 작성 시 공백으로만 작성할 수 없도록 변경하였습니다.
- 공백으로만 작성 시도 시 띄울 toast pop-up을 제작하였습니다.
> [230524] 토스트팝업 제작 및 적용

- src/apis/boardApi.ts
- src/components/board/Comments.tsx
- src/components/header/HeaderConstants.ts
- src/components/header/HeaderData.tsx
- src/components/modals/ReportModal.tsx
- src/components/navbar/Navbar.tsx
- src/pages/board/BoardDetail.tsx
- src/pages/report/ReportPage.tsx
> [230528] 신고하기 기능추가

- src/apis/mypageApi.ts
- src/atoms/atom.tsx
- src/components/board/CommandNavbar.tsx
- src/components/board/Comments.tsx
- src/components/header/Header.tsx
- src/components/header/HeaderConstants.ts
- src/components/header/HeaderData.tsx
- src/components/images/ImagesDetail.tsx
- src/components/modals/ProfileUpdateModal.tsx
- src/components/modals/StopEditModal.tsx
- src/components/mypage/MypagePopUp.tsx
- src/components/navbar/Navbar.tsx
- src/pages/board/BoardCreate.tsx
- src/pages/board/BoardDetail.tsx
- src/pages/mypage/MySetting.tsx
- src/pages/mypage/MypageConstants.ts
- src/pages/mypage/MypageUpdateForm.tsx
- src/pages/mypage/ResetPassward.tsx
- src/pages/mypage/ResetPassword.tsx
- src/pages/signin/SignIn.tsx
- src/pages/signin/SocialLogin.tsx
- src/pages/signup/SignUp.tsx
- src/routes/RoutePage.tsx
| feature 병합                             |          ✅             |
- 게시판 개행 수정
- 클릭 가능한 모든 요소에 cursor-pointer적용 및 클릭 가능영역 패딩 확장
- 글 작성 사진 추가 시 스크롤 이동 
- 프로필 이미지 업로드 문제 수정
- 비밀번호 재설정 기능 추가
> [230605] 프로필업로드 버그 수정 및 비밀번호 재설정 기능 추가

- src/pages/mypage/MypageUpdateForm.tsx
> Fix : 빌드에러 수정

- src/hooks/useInfiniteScroll.ts
- src/pages/board/BoardMain.tsx
- src/pages/mypage/MyCommentLog.tsx
- src/pages/mypage/MyPostLog.tsx
- 내 기록 조회에서 간헐적으로 발생하던 오류 수정했습니다. 무한스크롤 훅에서 queryKey 설정을 안해줘서 생긴 문제였습니다.
> Fix : 내 기록 조회 useInfiniteScroll 오류 수정

- src/components/board/CommandNavbar.tsx
- src/components/board/Comments.tsx
- src/components/header/Header.tsx
- src/pages/board/BoardDetail.tsx
- 라우터로 뒤로가기 클릭 시 모달이 뜨도록 했습니다.
- 글자가 삐죽나가는 오류를 수정했습니다.
- 페이지 이탈시 경고 모달을 띄우는 작업을 해야합니다.
> [230618] 기타 ui 오류 수정

- src/components/modals/Modals.tsx
- src/components/modals/NotificationModal.tsx
- src/components/modals/ProfileUpdateModal.tsx
[날짜] 기능 PR요청
- merge 요청자: @harimchung 
| feature 병합                             |         ✅              |
- 공지사항용 팝업 제작
- 사용 방법 예시 코드
- 일단 modal 형식으로 제작했는데 어떻게 하면 더 잘 사용할 수 있을 지 고민을 해봐야 할 것 같아요 :)
> [23.06.26] 공지사항 팝업 

- src/components/board/PostList.tsx
- 게시판 리스트 이미지 프리뷰
- 내글 조회 리스트 이미지 프리뷰
> [230730] 게시판 리스트 이미지 미리보기
